[build]
  publish = "frontend/dist"
  command = "rm -rf frontend/dist && cd frontend && npm ci && npm run build"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false